### PR TITLE
base files for alarm clock

### PR DESCRIPTION
**Pull request by eekimmai**

### CODE REVIEW

**Comment by eekimmai** [comment]
Hello! I saw some of the issues created by you, just wanted to contribute. The files are empty files, except for index.html which has a basic template, linking to css file and JS file.

**Comment by nerofor** [comment]
Hello. Sorry, I am learning use the GitHub and I have just realised your message. Yes, my files are empty. I develop step by step when I have enough time. Could you join my repository as contributor?

**Comment by eekimmai** [comment]
Hey, no worries and me too. I am also learning GitHub and saw your issue. I don’t mind helping but I am also new, to GitHub and coding too. If you look at my aboutme repository you can see it is not so good.  Anyways, i can help here and there

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nerofor** [comment]
Then I misunderstood it, sorry. I checked your aboutme repository and it is really elementary. But I like the 'Project 1'.

**Comment by eekimmai** [comment]
No problem and thanks. I can do my best to help with your alarm clock just raise the issue like you did earlier, if i am able i will contribute

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nerofor** [comment]
Okay, Thank you if you help me in the future.

**Pull request closed without merging**
